<?php

namespace SocialPro\NetworkBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * IssuesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IssuesRepository extends \Doctrine\ORM\EntityRepository
{
    public function byMax()
    {
        $query = $this->createQueryBuilder('s');
        $query->select('s, MIN(s.idIss) AS max_id');
        $query->groupBy('s.idIss');
        $query->setMaxResults(1);
        $query->orderBy('max_id', 'DESC');

        return $query->getQuery()->getResult();
    }

    public function rechercheIssuess($chaine)
    {
        $qb = $this->createQueryBuilder('i')
            ->select('i')
            ->where('i.type like :chaine')
            ->orderBy('i.idIss')
            ->setParameter('chaine', '%'. $chaine.'%');
        return $qb->getQuery()->getResult();
    }

}
